In [2]:
import torch
import numpy as np

In [7]:
t = np.array([[[0, 1, 2],
                          [3, 4, 6]],
                         [[6, 7, 8], [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.dim())

3


In [8]:
print(ft.view([-1, 3]))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  6.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [10]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  6.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [13]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft.squeeze())

tensor([0., 1., 2.])


In [18]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.unsqueeze(1))

tensor([[0.],
        [1.],
        [2.]])


In [19]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [20]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [22]:
val1 = torch.FloatTensor([[1, 2], [3, 4]])
val2 = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([val1, val2], dim=1))
print(torch.cat([val1, val2], dim=0))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [26]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [29]:
val1 = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(torch.ones_like(val1))
print(torch.zeros_like(val1))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [36]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
